export const MENU_ALL_LIST = "MENU_ALL_LIST";
export const MENU_HR_LIST = "MENU_HR_LIST";
export const MENU_LOGI_LIST = "MENU_LOGI_LIST";
export const MENU_ACCOUNT_LIST = "MENU_ACCOUNT_LIST";
export const MENU_LIST_REQUEST = "MENU_LIST_REQUEST";